/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_d_sodemo_JnI */

#ifndef _Included_com_d_sodemo_JnI
#define _Included_com_d_sodemo_JnI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_d_sodemo_JnI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_d_sodemo_JnI_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_d_sodemo_JnI
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_d_sodemo_JnI_unimplementedStringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
